#!/bin/sh

psql --host=localhost --username=postgres --command="CREATE DATABASE trigger_position_test;" --quiet 2>/dev/null \
  && psql --host=localhost --username=postgres --dbname=trigger_position_test --file=${0%/*}/../dist/trigger-position-structure.sql --quiet --set=ON_ERROR_STOP=1 \
  && psql --host=localhost --username=postgres --dbname=trigger_position_test --file=${0%/*}/../dist/trigger-position-control.sql --quiet --set=ON_ERROR_STOP=1 \
  && psql --host=localhost --username=postgres --dbname=trigger_position_test --file=${0%/*}/tests-structure.sql --quiet --set=ON_ERROR_STOP=1 \
  && psql --host=localhost --username=postgres --dbname=trigger_position_test --file=${0%/*}/test-table-without-group.sql --quiet --set=ON_ERROR_STOP=1 \
  && psql --host=localhost --username=postgres --dbname=trigger_position_test --file=${0%/*}/test-table-with-one-group.sql --quiet --set=ON_ERROR_STOP=1 \
  && psql --host=localhost --username=postgres --dbname=trigger_position_test --file=${0%/*}/test-table-with-two-groups.sql --quiet --set=ON_ERROR_STOP=1 \
  && psql --host=localhost --username=postgres --dbname=trigger_position_test --file=${0%/*}/test-alter-id-position-columns.sql --quiet --set=ON_ERROR_STOP=1;

psql --host=localhost --username=postgres --command="DROP DATABASE IF EXISTS trigger_position_test;" --quiet 2>/dev/null
